%YAML:1.0
# 0   - ICL
# 1~3 - TUM1~3
# 4   - SUN3D
# 5   - SUN3D_ORIGINAL
# 6   - PKU
dataset_type:    3

# Update type
# 0: Voxel projection
# 1: Ray casting
update_type: 0

# Raycasting mode
# 0: Standard raycasting (direction = camera-surfacepoint)
# 1: Ray casting with normal-induced truncation direction
raycasting_mode: 1

# -----------
enable_point_to_plane:  1
enable_directional_sdf: 0

enable_sdf_gradient:    1
enable_polygon_mode:    0

enable_color:           0
enable_navigation:      0
enable_global_mesh:     1
enable_bounding_box:    0
enable_trajectory:      1
enable_ray_casting:     0

enable_visualization:    0
enable_video_recording:  0
enable_block_saving:     0
enable_ply_saving:       1

filename_prefix: "burghers"
time_profile:    "tum3-nhm"
memo_profile:    "tum3-nhm"

# Others
run_frames:  -1
