%YAML:1.0
# 0   - ICL
# 1~3 - TUM1~3
# 4   - SUN3D
# 5   - SUN3D_ORIGINAL
# 6   - PKU
dataset_type:    4

# -----------
# Render options
free_walk:       0

# Polygon_mode draw triangle with only lines;
# otherwise with entire planes
ploygon_mode:    1

# 1 - in frustum
# 0 - in all
mesh_range:      0

# 0 - shaded map,
# 1 - entropy color map
render_type:     1
# If use shaded map, set it to 1
fine_gradient:   0

# Additional settings
bounding_box:    0
ray_casting:     0

# Result saving
record_video:    1
save_mesh:       1
filename_prefix: "copyroom-laplacian"

# Others
run_frames:      -1