%YAML:1.0
# 0   - ICL
# 1~3 - TUM1~3
# 4   - SUN3D
# 5   - SUN3D_ORIGINAL
# 6   - PKU
dataset_type:    4

# Render
free_walk:       0
line_only:       1
new_mesh_only:   0
fine_gradient:   0
# 0 for shaded map, 1 for entropy color map
render_type:     1

# Additional support
bounding_box:    0
ray_casting:     0

# Result saving
record_video:    1
save_mesh:       1
filename_prefix: "livingroom-only"

# Others
run_frames:      -1