%YAML:1.0
# 0   - ICL
# 1~3 - TUM1~3
# 4   - SUN3D
# 5   - SUN3D_ORIGINAL
# 6   - PKU
dataset_type:    4

# -----------
enable_bayesian_update: 1

enable_sdf_gradient:    1
enable_polygon_mode:    0

enable_color:           0
enable_navigation:      0
enable_global_mesh:     0
enable_bounding_box:    0
enable_trajectory:      0
enable_ray_casting:     0

enable_video_recording:  1
enable_ply_saving:       1

filename_prefix: "copyroom"
time_profile:    "tum3-nhm"
memo_profile:    "tum3-nhm"

# Others
run_frames:     100