%YAML:1.0

dataset_path:      "/home/wei/Work/data/3DVCR/lab4/"

# Hash params
bucket_count:      800000
bucket_size:       10
count:       8000000
linked_list_size:  7
value_capacity:    200000

# SDF params
voxel_size:                0.04
sdf_upper_bound:           4.0
truncation_distance_scale: 0.02
truncation_distance:       0.04
weight_sample:             10
weight_upper_bound:        255

# Sensor params
fx:              350.9285
fy:              350.2863
cx:              315.0930
cy:              173.4571
min_depth_range: 0.5
max_depth_range: 3.5
range_factor:    0.001
height:          360
width:           640

# Raycaster params
min_raycast_depth:    0.5
max_raycast_depth:    5.5
raycast_step:         0.016
sample_sdf_threshold: 0.808
sdf_threshold:        0.800
enable_gradient:      1

max_vertex_count:     10000000
max_triangle_count:   10000000