%YAML:1.0
fx:              525.0
fy:              525.0
cx:              319.5
cy:              239.5
min_depth_range: 0.5
max_depth_range: 2.0
range_factor:    0.001
height:          480
width:           640