%YAML:1.0
fx:              570.34
fy:              570.34
cx:              320.0
cy:              240.0
min_depth_range: 0.5
max_depth_range: 3.0
range_factor:    0.0002
height:          480
width:           640