%YAML:1.0

#dataset_path:      "/home/splietke/datasets/TUM/fr3/long_office_household/"
dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/cuboid_03_thin/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/sphere/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/armadillo/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/asian_dragon/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/bunny/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/dragon/"
#dataset_path:      "/home/splietke/projects/directionalTSDF/datasets/turbine_blade/"

# Hash params
bucket_count:      40000
bucket_size:       10
count:             400000
linked_list_size:  7
max_block_count:    300000

# SDF params
#voxel_size:                0.0025
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.000
#truncation_distance:       0.005

#voxel_size:                0.005
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.000
#truncation_distance:       0.020

voxel_size:                0.01
sdf_upper_bound:           4.0
truncation_distance_scale: 0.00
truncation_distance:       0.04

#voxel_size:                0.02
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.00
#truncation_distance:       0.08

#voxel_size:                0.03
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.00
#truncation_distance:       0.12

#voxel_size:                0.04
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.00
#truncation_distance:       0.16

#voxel_size:                0.05
#sdf_upper_bound:           5.0
#truncation_distance_scale: 0.00
#truncation_distance:       0.10

#voxel_size:                0.12
#sdf_upper_bound:           4.0
#truncation_distance_scale: 0.00
#truncation_distance:       0.24

weight_sample:             1
weight_upper_bound:        255

# Sensor params
fx:              525.0
fy:              525.0
cx:              319.5
cy:              239.5
min_depth_range: 0.5
max_depth_range: 4.0
range_factor:    0.0002
height:          480
width:           640

# Raycaster params
min_raycast_depth:    0.5
max_raycast_depth:    5.5
raycast_step:         0.016
sample_sdf_threshold: 0.808
sdf_threshold:        0.800
enable_gradient:      1

max_vertex_count:     400000
max_triangle_count:   800000
