/**
 * THIS IS A HACK TO SOLVE THE ISSUE WITH EIGEN3 REQUESTING THE DEPRECATED
 * math_functions.hpp
 */

#ifndef MESH_HASHING_MATH_FUNCTIONS_HPP
#define MESH_HASHING_MATH_FUNCTIONS_HPP

#include <cuda_runtime.h>

#endif //MESH_HASHING_MATH_FUNCTIONS_HPP
